Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,10 +27,11 @@ jobs:
           echo "environment is ${{ inputs.environment }}"
           echo "boolean is ${{ inputs.boolean }}"
           echo "choice is ${{ inputs.choice }}"
- bar_environment:
+
+jobs:
+  bar_environment:
     name: Build on BAR environment
     runs-on: ubuntu-latest
-    if: ${{ github.event.inputs.environment == 'BAR' }}
 
     steps:
       - name: Set up job
@@ -38,9 +39,14 @@ jobs:
 
       - name: Checkout repository
         uses: actions/checkout@v2
-      
+
       - name: Build on BAR environment
+        if: ${{ github.event.inputs.environment == 'BAR' }}
         run: echo "Hello, world!"
+
+      - name: Fail for unselected options
+        if: ${{ github.event.inputs.environment != 'BAR' }}
+        run: exit 78  # Exit with a failure code to halt execution
 
       - name: Post checkout repository
         run: echo "Post checkout repository"
@@ -48,10 +54,9 @@ jobs:
       - name: Complete job
         run: echo "Complete job"
 
- foo_environment:
+  foo_environment:
     name: Build on FOO environment
     runs-on: ubuntu-latest
-    if: ${{ github.event.inputs.environment == 'FOO' }}
 
     steps:
       - name: Set up job
@@ -59,8 +64,13 @@ jobs:
 
       - name: Checkout repository
         uses: actions/checkout@v2
-      
+
+      - name: Fail for unselected options
+        if: ${{ github.event.inputs.environment != 'FOO' }}
+        run: exit 78  # Exit with a failure code to halt execution
+
       - name: Build on FOO environment
+        if: ${{ github.event.inputs.environment == 'FOO' }}
         run: echo "I did the thing!"
 
       - name: Post checkout repository
@@ -68,25 +78,31 @@ jobs:
 
       - name: Complete job
         run: echo "Complete job"
- 
- ree_environment:
-     name: Build on REE environment
-     runs-on: ubuntu-latest
-     if: ${{ github.event.inputs.environment == 'REE' }}
 
-     steps:
-       - name: Set up job
-         run: echo "Set up job"
+  ree_environment:
+    name: Build on REE environment
+    runs-on: ubuntu-latest
 
-       - name: Checkout repository
-         uses: actions/checkout@v2
-      
-       - name: Build on REE environment
-         run: echo "This is the thing!"
+    steps:
+      - name: Set up job
+        run: echo "Set up job"
 
-       - name: Post checkout repository
-         run: echo "Post checkout repository"
+      - name: Checkout repository
+        uses: actions/checkout@v2
 
-       
-       
-        
+      - name: Fail for unselected options
+        if: ${{ github.event.inputs.environment != 'REE' }}
+        run: exit 78  # Exit with a failure code to halt execution
+
+      - name: Build on REE environment
+        if: ${{ github.event.inputs.environment == 'REE' }}
+        run: echo "This is the thing!"
+
+      - name: Post checkout repository
+        run: echo "Post checkout repository"
+
+      - name: Complete job
+        run: echo "Complete job"
+     
+     
+     
